### ISSUE TITLE
ENH: Inverse transform

### ISSUE THREAD

**Issue by victorxie996** [simaki/fracdiff#78] opened 2021-04-25 09:28 UTC
Hi! Thanks for sharing such nice code. I wonder if there is a way to inverse transform data back to original space? Obvisouly it is a tough work and I appreciate if you can point out some pausible directions.

**Comment by entropy43** [comment] 2021-04-25 09:56
It's absolutely possible. I'm not the package author but I'm happy to submit a pull request if there's interest.

**Comment by simaki** [comment] 2021-04-25 10:08
The inverse of `d`-th fracdiff is `-d`-th fracdiff because `(1-D)^(-n) (1-D)^n = 1` where `D` denotes a lag operator.
A caveat is, while this is mathematically true, practical computation of fracdiff truncates the Taylor expansion of `(1-D)`. So the above relation is approximate.

This library would run for negative `d`, but the validity of the output has not been tested.

**Comment by entropy43** [comment] 2021-04-25 10:14
I'd love to sharpen up this approximation with you (or at least compare notes). Shall we put together a practical reversal?

**Comment by simaki** [comment] 2021-04-25 13:24
@entropy43 Thank you!

The way I have come up is just to simply Taylor-expand `(1-D)^(-n)` with respect to `D` and then truncate the series in some order (or in other words window). I appreciate it if you could share some smarter way to sharpen this up.

**Comment by entropy43** [comment] 2021-04-25 22:49
@simaki I got more or less exact results via an implementation using [Mathematica's `Solve[]` function](https://reference.wolfram.com/language/ref/Solve.html). I'm sure we could do something similar using SymPy's solvers? What do you think?

**Comment by simaki** [comment] 2021-04-25 22:53
@entropy43 Awesome! Could you give some Mathematica code snippet so I can figure out the idea?

**Comment by entropy43** [comment] 2021-04-26 00:53
@simaki OK, I'm going to put something together. I can't remember off the top of my head but is there an easy way to pull out the frac diff weights from your function?

**Comment by simaki** [comment] 2021-04-26 00:54
@entropy43 yep, `fracdiff.base.fdiff_coef` would help.

**Comment by entropy43** [comment] 2021-04-26 02:15
Ok, so let's say I pull out the following for `1475.TSE` (using your example structure

```python
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pandas_datareader
import seaborn
import statsmodels.tsa.stattools as stattools
from fracdiff import Fracdiff, FracdiffStat, fdiff
from fracdiff.base import fdiff_coef
from pandas.plotting import register_matplotlib_converters

def fetch_yahoo(ticker, begin="1990-01-01", end="2020-12-31"):
    """
    Returns: pandas.Series
    """
    return pandas_datareader.data.DataReader(ticker, "yahoo", begin, end)["Adj Close"]
    
spx = fetch_yahoo("1475.T")
```
This returns a timeseries of length 1292
![image](https://user-images.githubusercontent.com/25653220/116020040-da1c8f80-a688-11eb-8af4-d85bd610845c.png)

I want to ensure I'm pulling out the coefficients right....so do I now just run

```python
fdiff_coef(fdiff,1292)
```

to pull out the coefficients?

**Comment by simaki** [comment] 2021-04-26 03:15
Thanks for sharing that. The first argument of fdiff_coef is order of fracdiff. May I ask how to approximate fracdiff inverse?

**Comment by entropy43** [comment] 2021-04-26 03:27
I'm putting it together now -- I just wanted to make sure I was getting the same coefficients as you so I could check.

**Comment by entropy43** [comment] 2021-04-26 04:58
@simaki Ok -- here is the solution. It is based on using "split" dot products. For my example on 'real' data I use the TOPIX ETF (1475.TSE)

### Import Data

Use your favourite method. I pull in `1475.TSE` from ~ 2015-12 to 2020-12-31

![image](https://user-images.githubusercontent.com/25653220/116029647-15c15480-a69d-11eb-8e0a-32a6251cc3f6.png)

### Determine fdiff parameters

Running your code to determine the optimal fdiff gives an fdiff with `d=.48`. We will use this `d` value 

### Determine Coefficients

From your `fdiff_coef(.48,9)` we return:

```python
[1,.48,-.1248,-.063232,-0.0398362, -0.0280447, -0.021127, -0.0166601, -0.013578]

```
and we then 'reverse' these

```python
wtsReversed = [-0.013578, -0.0166601, -0.021127, -0.0280447, -0.0398362, -0.063232, \
-0.1248, -0.48, 1.]

```
Plotting these produces the following:

![image](https://user-images.githubusercontent.com/25653220/116029898-abf57a80-a69d-11eb-9e9b-805cf1b98d4e.png)

So far, so good. From here on I use Mathematica

### Partition Price Data

`nCoeff = 9`

In Mathematica I then partition the price data into two sets, each overlapping by one

```mathematica

dateListPart = 
  Last[#] & /@ Partition[currentPxTS["Dates"], nCoeff + 1, 1];

valueListPartplus1 = Partition[currentPxTS["Values"], nCoeff + 1, 1];

valueListPart = Partition[currentPxTS["Values"], nCoeff, 1];

```
### Check the Next FDiff in the Partitioned Data

```mathematica

lastP = Last@valueListPart;

lastPplus1 = Last@valueListPartplus1;

nextFDiff = wtsReversed . lastP

Out[] = 397.244
```
### Create a Test Set frm the Last 100 Obs of Price Data

```mathematica

vList = valueListPart[[-100 ;;]];

wtdAll = # . wtsReversed & /@ vList;

wtd = wtdAll[[-100 ;;]];

wtd[[-5 ;;]]

Out[]= {387.77, 390.653, 398.141, 426.866, 397.244}
```
### Equation for Solution

I ditched using a solver in favour of the following dot-product-based function. Note, `Most` returns the tail of a list. For example, `Most[{1,2,3,4,5}]` will return `{2,3,4,5}`

```mathematica

priceCheck[partPx_, wt_, coeff_] := 
(
  eq2 = -(Most[partPx] . (Most[coeff]) - wt)/Last@coeff;
  {Last@partPx, eq2}
)

```

And now apply this function to the last 100 prices...this returns a tuple of the actual price and the reversed price -- in this case, they match 100%

```mathematica
priceCheck[vList[[#]], wtd[[#]], wtsReversed] & /@ Range@100

Out[]= {{1594., 1594.}, {1593., 1593.}, {1573., 1573.}, {1584., 
  1584.}, {1609., 1609.}, {1629., 1629.}, {1658., 1658.}, {1648., 
  1648.}, {1634., 1634.}, {1636., 1636.}, {1638., 1638.}, {1622., 
  1622.}, {1629., 1629.}, {1631., 1631.}, {1651., 1651.}, {1640., 
  1640.}, {1628., 1628.}, {1642., 1642.}, {1641., 1641.}, {1649., 
  1649.}, {1654., 1654.}, {1640., 1640.}, {1634., 1634.}, {1645., 
  1645.}, {1632., 1632.}, {1649., 1649.}, {1660., 1660.}, {1677., 
  1677.}, {1667., 1667.}, {1672., 1672.}, {1663., 1663.}, {1673., 
  1673.}, {1668., 1668.}, {1651., 1651.}, {1659., 1659.}, {1687., 
  1687.}, {1699., 1699.}, {1660., 1660.}, {1648., 1648.}, {1674., 
  1674.}, {1685., 1685.}, {1687., 1687.}, {1695., 1695.}, {1684., 
  1684.}, {1681., 1681.}, {1687., 1687.}, {1681., 1681.}, {1670., 
  1670.}, {1657., 1657.}, {1677., 1677.}, {1665., 1665.}, {1678., 
  1678.}, {1659., 1659.}, {1664., 1664.}, {1657., 1657.}, {1655., 
  1655.}, {1650., 1650.}, {1650., 1650.}, {1619., 1619.}, {1645., 
  1645.}, {1669., 1669.}, {1688., 1688.}, {1697., 1697.}, {1724., 
  1724.}, {1743., 1743.}, {1769., 1769.}, {1769., 1769.}, {1745., 
  1745.}, {1774., 1774.}, {1777., 1777.}, {1760., 1760.}, {1767., 
  1767.}, {1767., 1767.}, {1805., 1805.}, {1809., 1809.}, {1821., 
  1821.}, {1831., 1831.}, {1793., 1793.}, {1812., 1812.}, {1813., 
  1813.}, {1819., 1819.}, {1818., 1818.}, {1801., 1801.}, {1799., 
  1799.}, {1823., 1823.}, {1818., 1818.}, {1823., 1823.}, {1834., 
  1834.}, {1824., 1824.}, {1828., 1828.}, {1836., 1836.}, {1839., 
  1839.}, {1832., 1832.}, {1802., 1802.}, {1808., 1808.}, {1815., 
  1815.}, {1820., 1820.}, {1830., 1830.}, {1864., 1864.}, {1852., 
  1852.}}

```
What do you think? Does the job?

**Comment by simaki** [comment] 2021-04-26 05:54
@entropy43 
In my understanding that would be essentially: Let `y` be fracdiff of time-series `X`. Then `y = (1 - D)^d X = X - (c_1 D + c_2 D^2 + ...) X` (with `c_k` being binomial coefficients and `D` being backshift) and so `X = y + (c_1 D + c_2 D^2 + ...)X`.
But I'm afraid that may be technically something different from inverse; Inverse should reproduce `X` from `y` without referring to `X`. Rephrasing in terms of your Mathematica code, the inverse function must not refer to `partPx_`.

I'm not sure I'm interpreting the code correctly as I've pretty much never used Mathematica before. I appreciate it if you could point out my misunderstanding if there's any. Again, thank you a lot for sharing an idea and I'm happy to learn it.

**Comment by entropy43** [comment] 2021-04-26 06:07
@simaki Ahh; I just used the above to check. There is one more step. The final version (without referring to x) is as follows:

```mathematica
priceCheck2[partPx_, wt_, coeff_] := (
  eq2 = -(Rest[partPx] . (Most[coeff]) - wt)/Last@coeff;
  eq2)
```
Then substitute using "unseen" / T+1 data:


```mathematica
priceCheck3[vList[[-2]], Last@wtd, wtsReversed]

Out[] = 1852
```


And check by hand (we go to the [[-2]] and [[-1]] elements so we are not referring to X:

```mathematica
Rest[vList[[-2]]] . (Most[wtsReversed]) - Last@wtd

Most[vList[[-1]]] . (Most[wtsReversed]) - Last@wtd

Out[1] = -1852

Out[2] = -1852
```
Absolute value there is the unseen price.

Does that make sense? I think this is correct?

**Comment by simaki** [comment] 2021-04-26 06:16
I'm not sure I catch up. Could you let me know which function or equation is supposed to be an inverse?

**Comment by entropy43** [comment] 2021-04-26 09:00
Yes -- `priceCheck3` is where it's taking place.

This snippet shows how we calculate the next price ahead (`pxt`. `pxtm1` is T-1, `pxtm2` is T-2 etc ). We use prices up to t-1 (which were stored in `vList`). Today's predicted FD comes from `Last@wtd`. The coefficients come from `wtsReversed`

This snippet shows how the unknown `pxt` is isolated and calculated. IE (`fdnew-fdTemp)/k1`)

![image](https://user-images.githubusercontent.com/25653220/116056294-fb00d700-a6c0-11eb-9fe0-1237aa94469e.png)

**Comment by simaki** [comment] 2021-04-26 09:30
It seems priceCheck3 uses vList which is x.

**Comment by entropy43** [comment] 2021-04-27 01:35
I think it depends whether you want to use the geometric series or whether you want to use 'real' prices. I'm going to put together some examples today. There are some pros and cons. Will post more with examples later today.

**Comment by simaki** [comment] 2021-04-27 01:57
Thank you for sharing that, @entropy43! I have learned a lot 😄 

Hi @victorxie996, when you will find the way out or get something I can help with, please let me know anytime.

**Comment by simaki** [comment] 2021-04-29 04:32
closing until further updates.

**Closed by simaki** 2021-04-29 04:32 UTC
Labels: enhancement
